import {Platform, StyleSheet} from 'react-native';
import {Colors} from '../../Utilities/Styles/colors';
import commonStyles from '../../Utilities/Styles/commonStyles';
import fontFamily from '../../Utilities/Styles/fontFamily';
import {
  moderateScale,
  moderateScaleVertical,
  verticalScale,
  width,
} from '../../Utilities/Styles/responsiveSize';

const styles = StyleSheet.create({
  updateimgbtn: {
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignSelf: 'flex-end',
    bottom: 40,
    right: 10,
    padding: 10,
    borderRadius: 22,
  },
  profilecon: {
    backgroundColor: Colors.white,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    paddingTop: 20,
    paddingHorizontal: 20,
    top: -50,
  },
  profilecon1: {
    backgroundColor: Colors.white,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 5,
  },
  countrytxt: {
    fontSize: 12,
    fontFamily: fontFamily.regular,
    fontWeight: '400',
    color: Colors.black,
    marginLeft: 10,
  },
  countryimgcon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  datetxt: {
    fontSize: 10,
    fontFamily: fontFamily.regular,
    color: Colors.textgrey,
    fontWeight: '500',
    fontStyle: 'italic',
  },
  txtouterview: {
    backgroundColor: Colors.skyblue,
    padding: 10,
    borderRadius: 20,
    width: Platform.OS === 'ios' ? '90%' : '70%',
  },
  dateQuentityCon: {
    backgroundColor: Colors.skyblue,
    padding: 10,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  txtouterview1: {
    backgroundColor: Colors.skyblue,
    padding: 10,
    borderRadius: 20,
    width: Platform.OS === 'ios' ? '70%' : '60%',
  },
  dates: {
    fontSize: 12,
    fontFamily: fontFamily.regular,
    color: Colors.navyblue,
    fontWeight: '600',
    fontStyle: 'italic',
  },
  placeserveytxt: {
    fontSize: 12,
    fontFamily: fontFamily.regular,
    color: Colors.secondaryfont,
    fontWeight: '500',
    // textAlign: 'justify',
    lineHeight: 16,
  },
  overviewtxt: {
    fontSize: 14,
    fontFamily: fontFamily.regular,
    color: Colors.navyblue,
    fontWeight: '700',
  },
  dayphase: {
    fontSize: 12,
    fontFamily: fontFamily.regular,
    color: Colors.secondaryfont,
    fontWeight: '400',
    marginLeft: 15,
    flex:1,
    alignSelf:'flex-end',
    textAlign:'right',
  },
  button: {
    backgroundColor: Colors.navyblue,
    width: '90%',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 38,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  booknowbtn: {
    backgroundColor: Colors.primaryblue,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 38,
  },
  restrictionview: {
    backgroundColor: Colors.skyblue,
    padding: 15,
    borderRadius: 10,
    width: '90%',
    alignSelf: 'center',
  },
  restrictiontxt: {
    fontSize: 10,
    fontWeight: '400',
    fontFamily: fontFamily.regular,
    color: Colors.secondaryfont,
    textAlign: 'justify',
  },
  vectorcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    top: 15,
    right: 10,
    alignSelf: 'flex-end',
  },
  glancebtn: {
    backgroundColor: Colors.navyblue,
    padding: 10,
    borderRadius: 20,
    marginRight: 10,
  },
  btntxt: {
    fontSize: 10,
    fontWeight: '500',
    fontFamily: fontFamily.regular,
    color: Colors.white,
  },
  card: {
    flexDirection: 'row',
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
  },
  image: {
    width: moderateScale(100),
    height: moderateScaleVertical(86),
    borderRadius: 5,
  },

  textContainer: {
    marginLeft: 10,
    flex: 1,
  },
  description: {
    width: '100%',
  },
  overlay: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    padding: 20,
  },
  buttonText: {
    color: Colors.white,
    fontWeight: '600',
    fontSize: 12,
    fontFamily: fontFamily.regular,
  },
  tabcontainer: {
    width: moderateScaleVertical(25),
    height: moderateScale(25),
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
    position: 'absolute',
    top: 10,
    right: 10,
  },
  daytxt: {
    backgroundColor: Colors.white,
    borderRadius: 36,
    paddingVertical: 5,
    position: 'absolute',
    top: 10,
    left: 10,
    paddingHorizontal: 10,
  },
  title: {
    color: Colors.navyblue,
    fontSize: 12,
    fontWeight: '600',
    fontFamily: fontFamily.regular,
  },
  listContainer: {},
  selectedDayView: {
    backgroundColor: Colors.navyblue,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 15,
    marginRight: 5,
  },
  unselectedDayView: {
    backgroundColor: Colors.white,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 15,
    marginRight: 5,
  },
  selectedText: {
    fontSize: 10,
    fontWeight: '500',
    fontFamily: fontFamily.regular,
    color: Colors.white,
  },
  unselectedText: {
    fontSize: 10,
    fontWeight: '500',
    fontFamily: fontFamily.regular,
    color: Colors.secondaryfont,
  },
  outercon: {
    backgroundColor: Colors.white,
    padding: 15,
    borderRadius: 10,
  },
  standardbtn: {
    backgroundColor: Colors.primaryblue,
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginRight: 10,
    borderRadius: 20,
  },
  headerRow: {
    flexDirection: 'row',
    backgroundColor: '#3F87F5',
    paddingVertical: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    paddingHorizontal: 10,
  },
  dataRow: {
    flexDirection: 'row',
    backgroundColor: 'white',
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  text: {
    minWidth: 120,
    paddingVertical: 10,
    textAlign: 'center',
  },
  headerText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  dataText: {
    color: '#555',
    fontSize: 14,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
  },
  listview: {
    marginVertical: 10,
    alignItems: 'center',
    width: '50%',
  },
  listtitle: {
    ...commonStyles.font12,
    fontWeight: '700',
    textAlign: 'center',
  },
  tipsview: {
    paddingVertical: 5,
  },
  langbtn: {
    backgroundColor: Colors.primaryblue,
    borderRadius: 5,
    // height: 29,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  redoutervw: {
    borderWidth: 0.5,
    borderColor: Colors.red,
    width: 15,
    height: 15,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  datebtn: {
    height: 43,
    borderWidth: 1,
    borderColor: Colors.gentlegrey,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    justifyContent: 'space-between',
  },
  custombtn: {
    height: 41,
    borderRadius: 34,
    backgroundColor: Colors.navyblue,
    justifyContent: 'center',
  },
  bookingbtn: {
    height: 48,
    borderRadius: 34,
    backgroundColor: Colors.primaryblue,
    justifyContent: 'center',
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageContainer: {
    marginHorizontal: 8,
    borderRadius: 10,
    overflow: 'hidden',
  },
  imagess: {
    width: 200,
    height: 300,
    resizeMode: 'cover',
  },
  slide: {
    width: '100%',
    height: 400,
    borderRadius: 20,
    backgroundColor: 'white',
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  imgss: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    borderRadius: 20,
  },
  swiperview: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
    backgroundColor: Colors.white,
    shadowColor: Colors.black,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  scrollContainer: {
    flexDirection: 'row',
    paddingRight: moderateScale(10),
    paddingVertical: verticalScale(20),
  },
  flightSection: {
    backgroundColor: Colors.primaryblue,
    borderRadius: 10,
    padding: 15,
  },
  flightHeader: {},
  flightTitle: {
    ...commonStyles.font20navy,
    color: Colors.white,
  },
  flightList: {
    marginTop: 10,
  },
  flightText: {
    color: Colors.white,
    fontSize: 14,
    marginTop: 5,
    paddingVertical: verticalScale(5),
  },
  infoSection: {
    flex: 1,
    marginLeft: 15,
  },
  infoTitle: {
    ...commonStyles.font20navy,
    color: Colors.primaryblue,
    marginTop: 5,
  },
  infoList: {
    marginTop: 5,
  },
  infoText: {
    ...commonStyles.font12,
    color: Colors.black,
    marginTop: 5,
  },
  infoSubText: {
    color: Colors.black,
    fontSize: 12,
    opacity: 0.7,
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(5),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '80%',
    backgroundColor: Colors.navyblue,
    borderRadius: moderateScale(10),
    padding: moderateScale(10),
    maxHeight: '60%',
  },
  modalItem: {
    paddingVertical: moderateScale(10),
    borderBottomWidth: 1,
    borderBottomColor: Colors.gentlegrey,
  },
  modalText: {
    fontSize: moderateScale(14),
    color: Colors.white,
  },
  timelinesContainer: {
    flex: 1,
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  timelineBox: {
    backgroundColor: Colors.gentlegrey,
    borderRadius: 5,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 3,
  },
  timelineTextWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
    flex: 1,
    flexWrap: 'wrap',
  },
  timelineText: {
    ...commonStyles.font12Regualar2,
    flexShrink: 1,
  },
  timelineNumber: {
    ...commonStyles.font12Regualar2,
    fontWeight: 'bold',
    marginRight: 5,
  },
  optionalTourText: {
    ...commonStyles.font10Bold,
    marginRight: 5,
  },
  iconGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginLeft: 10,
  },
  timelineDescription: {
    ...commonStyles.font12Regualar2,
    marginLeft: 15,
    marginTop: 6,
    marginBottom: 10,
  },
  markerContainer: {
    width: 25,
    height: 30,
    alignItems: 'center',
    paddingTop: verticalScale(3),
  },
  markerImage: {
    width: 25,
    height: 30,
    resizeMode: 'contain',
  },
  markerText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  YoutbemodalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  closeButton: {
    marginTop: 10,
    padding: 10,
    backgroundColor: '#ff0000',
    borderRadius: 5,
  },
  closeButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  adddatebtn: {
    backgroundColor: Colors.skyblue,
    padding: 10,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
  },
  optionalTourCard: {
    width: '50%',
    backgroundColor: Colors.white,
    borderRadius: 10,
    alignItems: 'center',
    padding: 10,
  },
  optionalTourImage: {
    width: '100%',
    height: 100,
    borderRadius: 8,
  },
  optionalTourTitle: {
    ...commonStyles.font10Regular,
    textAlign: 'center',
    color: Colors.navyblue,
  },
  optionalTourButton: {
    backgroundColor: Colors.primaryblue,
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginTop: moderateScaleVertical(5),
    alignSelf: 'center',
  },
  optionalTourButtonText: {
    ...commonStyles.font10Bold,
    color: Colors.white,
    textAlign: 'center',
  },
  iconCard: {
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  iconImage: {
    width: 50,
    height: 50,
  },
  iconText: {
    marginTop: 6,
    fontSize: 12,
    color: '#333',
    textAlign: 'center',
  },
  // Enhanced Airfare and Transportation Styles
  airfareContainer: {
    backgroundColor: Colors.white,
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
  },
  airfareIntroText: {
    ...commonStyles.font12Regualar2,
    color: Colors.secondaryfont,
    marginBottom: 15,
    lineHeight: 18,
  },
  airfareFlightCardsContainer: {
    flexDirection: 'row',
    gap: moderateScale(12),
    paddingRight: moderateScale(20),
  },
  airfareFlightCard: {
    backgroundColor: Colors.skyblue,
    borderRadius: 12,
    padding: 14,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primaryblue,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 3,
    minWidth: moderateScale(250),
  },
  airfareFlightNumber: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.primaryblue,
    marginBottom: 8,
  },
  airfareDetailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
    gap: moderateScale(6),
  },
  airfareDetailLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: Colors.navyblue,
    minWidth: 32,
  },
  airfareDetailValue: {
    fontSize: 9,
    fontWeight: '400',
    color: Colors.secondaryfont,
    flex: 1,
  },
  airfareIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.1)',
  },
  airfareIcon: {
    alignItems: 'center',
    gap: 5,
  },
  airfareIconText: {
    ...commonStyles.font10Bold,
    color: Colors.primaryblue,
    textAlign: 'center',
  },
  airfareNoDataCard: {
    backgroundColor: Colors.skyblue,
    borderRadius: 10,
    padding: 15,
    borderLeftWidth: 5,
    borderLeftColor: Colors.primaryblue,
  },
  airfareNoDataText: {
    ...commonStyles.font12Regualar2,
    color: Colors.secondaryfont,
    lineHeight: 18,
    textAlign: 'justify',
  },
  airfareCarouselContainer: {
    marginVertical: 10,
  },
  airfareCarouselItemContainer: {
    width: width,
    justifyContent: 'center',
  },
  airfareCarouselItem: {
    backgroundColor: Colors.skyblue,
    borderRadius: 12,
    padding: 16,
    paddingHorizontal: 20,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primaryblue,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.12,
    shadowRadius: 4,
    width: '85%',
  },
  airfareCarouselIndicatorContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    gap: 6,
  },
  airfareCarouselIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.gentlegrey,
  },
  airfareCarouselIndicatorActive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.primaryblue,
  },
});

export default styles;
